DATAPATH=$(CURDIR)/data

download-data:
	mkdir $(DATAPATH)
	curl http://snap.stanford.edu/data/amazon/productGraph/categoryFiles/reviews_Toys_and_Games_5.json.gz -o $(DATAPATH)/reviews_Toys_and_Games_5.json.gz
	curl http://snap.stanford.edu/data/amazon/productGraph/categoryFiles/reviews_Sports_and_Outdoors_5.json.gz -o $(DATAPATH)/reviews_Sports_and_Outdoors_5.json.gz
	curl http://snap.stanford.edu/data/amazon/productGraph/categoryFiles/reviews_Movies_and_TV_5.json.gz -o $(DATAPATH)/reviews_Movies_and_TV_5.json.gz
